/** Common crypto symbol → human name mapping, shared across all adapters. */
export const SYMBOL_NAMES: Record<string, string> = {
  BTC: "Bitcoin",
  ETH: "Ethereum",
  BNB: "BNB",
  SOL: "Solana",
  XRP: "XRP",
  ADA: "Cardano",
  DOGE: "Dogecoin",
  AVAX: "Avalanche",
  DOT: "Polkadot",
  MATIC: "Polygon",
  POL: "Polygon",
  LINK: "Chainlink",
  LTC: "Litecoin",
  UNI: "Uniswap",
  ATOM: "Cosmos",
  XLM: "Stellar",
  ETC: "Ethereum Classic",
  BCH: "Bitcoin Cash",
  ALGO: "Algorand",
  VET: "VeChain",
  FIL: "Filecoin",
  TRX: "TRON",
  NEAR: "NEAR Protocol",
  APT: "Aptos",
  ARB: "Arbitrum",
  OP: "Optimism",
  INJ: "Injective",
  SUI: "Sui",
  SHIB: "Shiba Inu",
  PEPE: "Pepe",
  TON: "Toncoin",
  USDT: "Tether",
  USDC: "USD Coin",
  BUSD: "Binance USD",
  FDUSD: "First Digital USD",
  DAI: "Dai",
  CRO: "Cronos",
  AAVE: "Aave",
  MKR: "Maker",
  SNX: "Synthetix",
  COMP: "Compound",
  GRT: "The Graph",
  SAND: "The Sandbox",
  MANA: "Decentraland",
  AXS: "Axie Infinity",
  HBAR: "Hedera",
  ICP: "Internet Computer",
  FTM: "Fantom",
  THETA: "Theta Network",
  XTZ: "Tezos",
  EOS: "EOS",
  FLOW: "Flow",
  EGLD: "MultiversX",
  KAVA: "Kava",
  ZEC: "Zcash",
  DASH: "Dash",
  NEO: "Neo",
  WAVES: "Waves",
  XMR: "Monero",
  KCS: "KuCoin Token",
  SFP: "SafePal",
};

export const STABLECOINS = new Set(["USDT", "USDC", "BUSD", "FDUSD", "DAI", "TUSD", "UST", "PYUSD"]);

export function getSymbolName(symbol: string): string {
  return SYMBOL_NAMES[symbol] ?? symbol;
}
